// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger/rwset/kvrwset/kv_rwset.proto

/*
Package kvrwset is a generated protocol buffer package.

It is generated from these files:
	ledger/rwset/kvrwset/kv_rwset.proto

It has these top-level messages:
	KVRWSet
	HashedRWSet
	KVRead
	KVWrite
	KVReadHash
	KVWriteHash
	Version
	RangeQueryInfo
	QueryReads
	QueryReadsMerkleSummary
*/
package kvrwset

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// KVRWSet encapsulates the read-write set for a chaincode that operates upon a KV or Document data model
// This structure is used for both the public data and the private data
type KVRWSet struct {
	Reads            []*KVRead         `protobuf:"bytes,1,rep,name=reads" json:"reads,omitempty"`
	RangeQueriesInfo []*RangeQueryInfo `protobuf:"bytes,2,rep,name=range_queries_info,json=rangeQueriesInfo" json:"range_queries_info,omitempty"`
	Writes           []*KVWrite        `protobuf:"bytes,3,rep,name=writes" json:"writes,omitempty"`
}

func (m *KVRWSet) Reset()                    { *m = KVRWSet{} }
func (m *KVRWSet) String() string            { return proto.CompactTextString(m) }
func (*KVRWSet) ProtoMessage()               {}
func (*KVRWSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KVRWSet) GetReads() []*KVRead {
	if m != nil {
		return m.Reads
	}
	return nil
}

func (m *KVRWSet) GetRangeQueriesInfo() []*RangeQueryInfo {
	if m != nil {
		return m.RangeQueriesInfo
	}
	return nil
}

func (m *KVRWSet) GetWrites() []*KVWrite {
	if m != nil {
		return m.Writes
	}
	return nil
}

// HashedRWSet encapsulates hashed representation of a private read-write set for KV or Document data model
type HashedRWSet struct {
	HashedReads  []*KVReadHash  `protobuf:"bytes,2,rep,name=hashed_reads,json=hashedReads" json:"hashed_reads,omitempty"`
	HashedWrites []*KVWriteHash `protobuf:"bytes,3,rep,name=hashed_writes,json=hashedWrites" json:"hashed_writes,omitempty"`
}

func (m *HashedRWSet) Reset()                    { *m = HashedRWSet{} }
func (m *HashedRWSet) String() string            { return proto.CompactTextString(m) }
func (*HashedRWSet) ProtoMessage()               {}
func (*HashedRWSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HashedRWSet) GetHashedReads() []*KVReadHash {
	if m != nil {
		return m.HashedReads
	}
	return nil
}

func (m *HashedRWSet) GetHashedWrites() []*KVWriteHash {
	if m != nil {
		return m.HashedWrites
	}
	return nil
}

// KVRead captures a read operation performed during transaction simulation
// A 'nil' version indicates a non-existing key read by the transaction
type KVRead struct {
	Key     string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Version *Version `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *KVRead) Reset()                    { *m = KVRead{} }
func (m *KVRead) String() string            { return proto.CompactTextString(m) }
func (*KVRead) ProtoMessage()               {}
func (*KVRead) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *KVRead) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVRead) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

// KVWrite captures a write (update/delete) operation performed during transaction simulation
type KVWrite struct {
	Key      string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	IsDelete bool   `protobuf:"varint,2,opt,name=is_delete,json=isDelete" json:"is_delete,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *KVWrite) Reset()                    { *m = KVWrite{} }
func (m *KVWrite) String() string            { return proto.CompactTextString(m) }
func (*KVWrite) ProtoMessage()               {}
func (*KVWrite) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *KVWrite) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVWrite) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func (m *KVWrite) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// KVReadHash is similar to the KVRead in spirit. However, it captures the hash of the key instead of the key itself
// version is kept as is for now. However, if the version also needs to be privacy-protected, it would need to be the
// hash of the version and hence of 'bytes' type
type KVReadHash struct {
	KeyHash []byte   `protobuf:"bytes,1,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	Version *Version `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *KVReadHash) Reset()                    { *m = KVReadHash{} }
func (m *KVReadHash) String() string            { return proto.CompactTextString(m) }
func (*KVReadHash) ProtoMessage()               {}
func (*KVReadHash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *KVReadHash) GetKeyHash() []byte {
	if m != nil {
		return m.KeyHash
	}
	return nil
}

func (m *KVReadHash) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

// KVWriteHash is similar to the KVWrite in spiritcaptures a write (update/delete) operation performed during transaction simulation
type KVWriteHash struct {
	KeyHash   []byte `protobuf:"bytes,1,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	IsDelete  bool   `protobuf:"varint,2,opt,name=is_delete,json=isDelete" json:"is_delete,omitempty"`
	ValueHash []byte `protobuf:"bytes,3,opt,name=value_hash,json=valueHash,proto3" json:"value_hash,omitempty"`
}

func (m *KVWriteHash) Reset()                    { *m = KVWriteHash{} }
func (m *KVWriteHash) String() string            { return proto.CompactTextString(m) }
func (*KVWriteHash) ProtoMessage()               {}
func (*KVWriteHash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *KVWriteHash) GetKeyHash() []byte {
	if m != nil {
		return m.KeyHash
	}
	return nil
}

func (m *KVWriteHash) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func (m *KVWriteHash) GetValueHash() []byte {
	if m != nil {
		return m.ValueHash
	}
	return nil
}

// Version encapsulates the version of a Key
// A version of a committed key is maintained as the height of the transaction that committed the key.
// The height is represenetd as a tuple <blockNum, txNum> where the txNum is the height of the transaction
// (starting with 1) within block
type Version struct {
	BlockNum uint64 `protobuf:"varint,1,opt,name=block_num,json=blockNum" json:"block_num,omitempty"`
	TxNum    uint64 `protobuf:"varint,2,opt,name=tx_num,json=txNum" json:"tx_num,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Version) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *Version) GetTxNum() uint64 {
	if m != nil {
		return m.TxNum
	}
	return 0
}

// RangeQueryInfo encapsulates the details of a range query performed by a transaction during simulation.
// This helps protect transactions from phantom reads by varifying during validation whether any new items
// got committed within the given range between transaction simuation and validation
// (in addition to regular checks for updates/deletes of the existing items).
// readInfo field contains either the KVReads (for the items read by the range query) or a merkle-tree hash
// if the KVReads exceeds a pre-configured numbers
type RangeQueryInfo struct {
	StartKey     string `protobuf:"bytes,1,opt,name=start_key,json=startKey" json:"start_key,omitempty"`
	EndKey       string `protobuf:"bytes,2,opt,name=end_key,json=endKey" json:"end_key,omitempty"`
	ItrExhausted bool   `protobuf:"varint,3,opt,name=itr_exhausted,json=itrExhausted" json:"itr_exhausted,omitempty"`
	// Types that are valid to be assigned to ReadsInfo:
	//	*RangeQueryInfo_RawReads
	//	*RangeQueryInfo_ReadsMerkleHashes
	ReadsInfo isRangeQueryInfo_ReadsInfo `protobuf_oneof:"reads_info"`
}

func (m *RangeQueryInfo) Reset()                    { *m = RangeQueryInfo{} }
func (m *RangeQueryInfo) String() string            { return proto.CompactTextString(m) }
func (*RangeQueryInfo) ProtoMessage()               {}
func (*RangeQueryInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type isRangeQueryInfo_ReadsInfo interface {
	isRangeQueryInfo_ReadsInfo()
}

type RangeQueryInfo_RawReads struct {
	RawReads *QueryReads `protobuf:"bytes,4,opt,name=raw_reads,json=rawReads,oneof"`
}
type RangeQueryInfo_ReadsMerkleHashes struct {
	ReadsMerkleHashes *QueryReadsMerkleSummary `protobuf:"bytes,5,opt,name=reads_merkle_hashes,json=readsMerkleHashes,oneof"`
}

func (*RangeQueryInfo_RawReads) isRangeQueryInfo_ReadsInfo()          {}
func (*RangeQueryInfo_ReadsMerkleHashes) isRangeQueryInfo_ReadsInfo() {}

func (m *RangeQueryInfo) GetReadsInfo() isRangeQueryInfo_ReadsInfo {
	if m != nil {
		return m.ReadsInfo
	}
	return nil
}

func (m *RangeQueryInfo) GetStartKey() string {
	if m != nil {
		return m.StartKey
	}
	return ""
}

func (m *RangeQueryInfo) GetEndKey() string {
	if m != nil {
		return m.EndKey
	}
	return ""
}

func (m *RangeQueryInfo) GetItrExhausted() bool {
	if m != nil {
		return m.ItrExhausted
	}
	return false
}

func (m *RangeQueryInfo) GetRawReads() *QueryReads {
	if x, ok := m.GetReadsInfo().(*RangeQueryInfo_RawReads); ok {
		return x.RawReads
	}
	return nil
}

func (m *RangeQueryInfo) GetReadsMerkleHashes() *QueryReadsMerkleSummary {
	if x, ok := m.GetReadsInfo().(*RangeQueryInfo_ReadsMerkleHashes); ok {
		return x.ReadsMerkleHashes
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RangeQueryInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RangeQueryInfo_OneofMarshaler, _RangeQueryInfo_OneofUnmarshaler, _RangeQueryInfo_OneofSizer, []interface{}{
		(*RangeQueryInfo_RawReads)(nil),
		(*RangeQueryInfo_ReadsMerkleHashes)(nil),
	}
}

func _RangeQueryInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RangeQueryInfo)
	// reads_info
	switch x := m.ReadsInfo.(type) {
	case *RangeQueryInfo_RawReads:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RawReads); err != nil {
			return err
		}
	case *RangeQueryInfo_ReadsMerkleHashes:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReadsMerkleHashes); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RangeQueryInfo.ReadsInfo has unexpected type %T", x)
	}
	return nil
}

func _RangeQueryInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RangeQueryInfo)
	switch tag {
	case 4: // reads_info.raw_reads
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(QueryReads)
		err := b.DecodeMessage(msg)
		m.ReadsInfo = &RangeQueryInfo_RawReads{msg}
		return true, err
	case 5: // reads_info.reads_merkle_hashes
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(QueryReadsMerkleSummary)
		err := b.DecodeMessage(msg)
		m.ReadsInfo = &RangeQueryInfo_ReadsMerkleHashes{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RangeQueryInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RangeQueryInfo)
	// reads_info
	switch x := m.ReadsInfo.(type) {
	case *RangeQueryInfo_RawReads:
		s := proto.Size(x.RawReads)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RangeQueryInfo_ReadsMerkleHashes:
		s := proto.Size(x.ReadsMerkleHashes)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// QueryReads encapsulates the KVReads for the items read by a transaction as a result of a query execution
type QueryReads struct {
	KvReads []*KVRead `protobuf:"bytes,1,rep,name=kv_reads,json=kvReads" json:"kv_reads,omitempty"`
}

func (m *QueryReads) Reset()                    { *m = QueryReads{} }
func (m *QueryReads) String() string            { return proto.CompactTextString(m) }
func (*QueryReads) ProtoMessage()               {}
func (*QueryReads) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *QueryReads) GetKvReads() []*KVRead {
	if m != nil {
		return m.KvReads
	}
	return nil
}

// QueryReadsMerkleSummary encapsulates the Merkle-tree hashes for the QueryReads
// This allows to reduce the size of RWSet in the presence of query results
// by storing certain hashes instead of actual results.
// maxDegree field refers to the maximum number of children in the tree at any level
// maxLevel field contains the lowest level which has lesser nodes than maxDegree (starting from leaf level)
type QueryReadsMerkleSummary struct {
	MaxDegree      uint32   `protobuf:"varint,1,opt,name=max_degree,json=maxDegree" json:"max_degree,omitempty"`
	MaxLevel       uint32   `protobuf:"varint,2,opt,name=max_level,json=maxLevel" json:"max_level,omitempty"`
	MaxLevelHashes [][]byte `protobuf:"bytes,3,rep,name=max_level_hashes,json=maxLevelHashes,proto3" json:"max_level_hashes,omitempty"`
}

func (m *QueryReadsMerkleSummary) Reset()                    { *m = QueryReadsMerkleSummary{} }
func (m *QueryReadsMerkleSummary) String() string            { return proto.CompactTextString(m) }
func (*QueryReadsMerkleSummary) ProtoMessage()               {}
func (*QueryReadsMerkleSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *QueryReadsMerkleSummary) GetMaxDegree() uint32 {
	if m != nil {
		return m.MaxDegree
	}
	return 0
}

func (m *QueryReadsMerkleSummary) GetMaxLevel() uint32 {
	if m != nil {
		return m.MaxLevel
	}
	return 0
}

func (m *QueryReadsMerkleSummary) GetMaxLevelHashes() [][]byte {
	if m != nil {
		return m.MaxLevelHashes
	}
	return nil
}

func init() {
	proto.RegisterType((*KVRWSet)(nil), "kvrwset.KVRWSet")
	proto.RegisterType((*HashedRWSet)(nil), "kvrwset.HashedRWSet")
	proto.RegisterType((*KVRead)(nil), "kvrwset.KVRead")
	proto.RegisterType((*KVWrite)(nil), "kvrwset.KVWrite")
	proto.RegisterType((*KVReadHash)(nil), "kvrwset.KVReadHash")
	proto.RegisterType((*KVWriteHash)(nil), "kvrwset.KVWriteHash")
	proto.RegisterType((*Version)(nil), "kvrwset.Version")
	proto.RegisterType((*RangeQueryInfo)(nil), "kvrwset.RangeQueryInfo")
	proto.RegisterType((*QueryReads)(nil), "kvrwset.QueryReads")
	proto.RegisterType((*QueryReadsMerkleSummary)(nil), "kvrwset.QueryReadsMerkleSummary")
}

func init() { proto.RegisterFile("ledger/rwset/kvrwset/kv_rwset.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x8d, 0xec, 0xd8, 0x92, 0xc7, 0x76, 0xea, 0x6e, 0x52, 0xa2, 0x52, 0x0a, 0x46, 0xa1, 0x60,
	0x72, 0x90, 0x21, 0x85, 0xd2, 0x1c, 0x7a, 0x29, 0x49, 0x49, 0x49, 0x1b, 0xe8, 0x06, 0x12, 0xe8,
	0x45, 0xac, 0xa3, 0x89, 0x2d, 0xf4, 0x95, 0xee, 0x4a, 0xb6, 0x75, 0x6a, 0xfb, 0x53, 0xfa, 0x4f,
	0xcb, 0xce, 0xca, 0x71, 0x12, 0xd2, 0x40, 0x4f, 0xd6, 0xbe, 0x37, 0x6f, 0xe6, 0xcd, 0x78, 0x76,
	0x61, 0x2f, 0xc1, 0x70, 0x8a, 0x72, 0x2c, 0x17, 0x0a, 0x8b, 0x71, 0x3c, 0x5f, 0xfd, 0x06, 0xf4,
	0xe1, 0xdf, 0xc8, 0xbc, 0xc8, 0x99, 0x5d, 0xe3, 0xde, 0x1f, 0x0b, 0xec, 0xd3, 0x0b, 0x7e, 0x79,
	0x8e, 0x05, 0x7b, 0x03, 0x2d, 0x89, 0x22, 0x54, 0xae, 0x35, 0x6c, 0x8e, 0xba, 0x07, 0xcf, 0xfc,
	0x3a, 0xc8, 0x3f, 0xbd, 0xe0, 0x28, 0x42, 0x6e, 0x58, 0x76, 0x0c, 0x4c, 0x8a, 0x6c, 0x8a, 0xc1,
	0x8f, 0x12, 0x65, 0x84, 0x2a, 0x88, 0xb2, 0xeb, 0xdc, 0x6d, 0x90, 0x66, 0xf7, 0x56, 0xc3, 0x75,
	0xc8, 0xb7, 0x12, 0x65, 0xf5, 0x39, 0xbb, 0xce, 0xf9, 0x40, 0xae, 0xce, 0x11, 0x2a, 0x8d, 0xb0,
	0x11, 0xb4, 0x17, 0x32, 0x2a, 0x50, 0xb9, 0x4d, 0x92, 0x0e, 0xee, 0x94, 0xbb, 0xd4, 0x04, 0xaf,
	0x79, 0xef, 0x97, 0x05, 0xdd, 0x13, 0xa1, 0x66, 0x18, 0x1a, 0x9f, 0xef, 0xa0, 0x37, 0xa3, 0x63,
	0x60, 0xec, 0x9a, 0xd2, 0xdb, 0x0f, 0xec, 0x6a, 0x05, 0xef, 0x9a, 0x40, 0x4e, 0xc6, 0x0f, 0xa1,
	0x5f, 0xeb, 0xee, 0x15, 0xde, 0x79, 0x58, 0x98, 0x94, 0x75, 0x89, 0x4b, 0x63, 0xe1, 0x13, 0xb4,
	0x4d, 0x56, 0x36, 0x80, 0x66, 0x8c, 0x95, 0x6b, 0x0d, 0xad, 0x51, 0x87, 0xeb, 0x4f, 0xb6, 0x0f,
	0xf6, 0x1c, 0xa5, 0x8a, 0xf2, 0xcc, 0x6d, 0x0c, 0xad, 0x7b, 0x9d, 0x5c, 0x18, 0x9c, 0xaf, 0x02,
	0xbc, 0x33, 0x3d, 0x6d, 0xca, 0xf9, 0x48, 0xa2, 0x57, 0xd0, 0x89, 0x54, 0x10, 0x62, 0x82, 0x05,
	0x52, 0x2a, 0x87, 0x3b, 0x91, 0x3a, 0xa2, 0x33, 0xdb, 0x81, 0xd6, 0x5c, 0x24, 0x25, 0xba, 0xcd,
	0xa1, 0x35, 0xea, 0x71, 0x73, 0xf0, 0xce, 0x01, 0xd6, 0xdd, 0xb2, 0x97, 0xe0, 0xc4, 0x58, 0x05,
	0xda, 0x39, 0xe5, 0xed, 0x71, 0x3b, 0xc6, 0x8a, 0xa8, 0xff, 0x31, 0x19, 0x42, 0xf7, 0xce, 0x24,
	0x9e, 0xca, 0xfa, 0xa4, 0xe3, 0xd7, 0x00, 0x64, 0xd2, 0x28, 0x8d, 0xed, 0x0e, 0x21, 0x5a, 0xeb,
	0x7d, 0x00, 0xbb, 0xae, 0xac, 0xd3, 0x4c, 0x92, 0xfc, 0x2a, 0x0e, 0xb2, 0x32, 0xa5, 0x12, 0x9b,
	0xdc, 0x21, 0xe0, 0xac, 0x4c, 0xd9, 0x0b, 0x68, 0x17, 0x4b, 0x62, 0x1a, 0xc4, 0xb4, 0x8a, 0xe5,
	0x59, 0x99, 0x7a, 0xbf, 0x1b, 0xb0, 0x75, 0x7f, 0xc7, 0x74, 0x1a, 0x55, 0x08, 0x59, 0x04, 0xeb,
	0xb9, 0x3a, 0x04, 0x9c, 0x62, 0xc5, 0x76, 0xc1, 0xc6, 0x2c, 0x24, 0xaa, 0x41, 0x54, 0x1b, 0xb3,
	0x50, 0x13, 0x7b, 0xd0, 0x8f, 0x0a, 0x19, 0xe0, 0x72, 0x26, 0x4a, 0x55, 0x60, 0x48, 0x4e, 0x1d,
	0xde, 0x8b, 0x0a, 0x79, 0xbc, 0xc2, 0xd8, 0x01, 0x74, 0xa4, 0x58, 0xd4, 0xfb, 0xb6, 0x49, 0x03,
	0x5c, 0xef, 0x1b, 0x39, 0xa0, 0x15, 0x3b, 0xd9, 0xe0, 0x8e, 0x14, 0x0b, 0xb3, 0x6e, 0x1c, 0xb6,
	0x29, 0x3e, 0x48, 0x51, 0xc6, 0x89, 0x19, 0x03, 0x2a, 0xb7, 0x45, 0xea, 0xe1, 0x23, 0xea, 0xaf,
	0x14, 0x77, 0x5e, 0xa6, 0xa9, 0x90, 0xd5, 0xc9, 0x06, 0x7f, 0x2e, 0xd7, 0x28, 0xed, 0xbf, 0xfa,
	0xd8, 0x03, 0x30, 0x39, 0xf5, 0x9d, 0xf3, 0xde, 0x03, 0xac, 0xd5, 0x6c, 0x1f, 0x1c, 0x7d, 0xcb,
	0x9f, 0xba, 0xc1, 0x76, 0x3c, 0xa7, 0x58, 0xef, 0x27, 0xec, 0xfe, 0xa3, 0xae, 0xfe, 0xdb, 0x52,
	0xb1, 0x0c, 0x42, 0x9c, 0x4a, 0x44, 0x1a, 0x63, 0x9f, 0x77, 0x52, 0xb1, 0x3c, 0x22, 0x40, 0x0f,
	0x59, 0xd3, 0x09, 0xce, 0x31, 0xa1, 0x49, 0xf6, 0xb9, 0x93, 0x8a, 0xe5, 0x17, 0x7d, 0x66, 0x23,
	0x18, 0xdc, 0x92, 0xab, 0x7e, 0xf5, 0x25, 0xeb, 0xf1, 0xad, 0x55, 0x4c, 0xdd, 0x48, 0x0e, 0x07,
	0xb9, 0x9c, 0xfa, 0xb3, 0xea, 0x06, 0xa5, 0x79, 0xb0, 0xfc, 0x6b, 0x31, 0x91, 0xd1, 0x95, 0x79,
	0xa0, 0x94, 0x5f, 0x83, 0xc6, 0x7e, 0xdd, 0xc6, 0xf7, 0xc3, 0x69, 0x54, 0xcc, 0xca, 0x89, 0x7f,
	0x95, 0xa7, 0xe3, 0x3b, 0xd2, 0xb1, 0x91, 0x8e, 0x8d, 0x74, 0xfc, 0xd8, 0x03, 0x38, 0x69, 0x13,
	0xf9, 0xf6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x3a, 0x6f, 0xe0, 0x1f, 0x05, 0x00, 0x00,
}
