// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger/rwset/rwset.proto

/*
Package rwset is a generated protocol buffer package.

It is generated from these files:
	ledger/rwset/rwset.proto

It has these top-level messages:
	TxReadWriteSet
	NsReadWriteSet
	CollectionHashedReadWriteSet
	TxPvtReadWriteSet
	NsPvtReadWriteSet
	CollectionPvtReadWriteSet
*/
package rwset

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxReadWriteSet_DataModel int32

const (
	TxReadWriteSet_KV TxReadWriteSet_DataModel = 0
)

var TxReadWriteSet_DataModel_name = map[int32]string{
	0: "KV",
}
var TxReadWriteSet_DataModel_value = map[string]int32{
	"KV": 0,
}

func (x TxReadWriteSet_DataModel) String() string {
	return proto.EnumName(TxReadWriteSet_DataModel_name, int32(x))
}
func (TxReadWriteSet_DataModel) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// TxReadWriteSet encapsulates a read-write set for a transaction
// DataModel specifies the enum value of the data model
// ns_rwset field specifies a list of chaincode specific read-write set (one for each chaincode)
type TxReadWriteSet struct {
	DataModel               TxReadWriteSet_DataModel `protobuf:"varint,1,opt,name=data_model,json=dataModel,enum=rwset.TxReadWriteSet_DataModel" json:"data_model,omitempty"`
	NsRwset                 []*NsReadWriteSet        `protobuf:"bytes,2,rep,name=ns_rwset,json=nsRwset" json:"ns_rwset,omitempty"`
	PrivateReadwritesetHash []byte                   `protobuf:"bytes,3,opt,name=private_readwriteset_hash,json=privateReadwritesetHash,proto3" json:"private_readwriteset_hash,omitempty"`
}

func (m *TxReadWriteSet) Reset()                    { *m = TxReadWriteSet{} }
func (m *TxReadWriteSet) String() string            { return proto.CompactTextString(m) }
func (*TxReadWriteSet) ProtoMessage()               {}
func (*TxReadWriteSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TxReadWriteSet) GetDataModel() TxReadWriteSet_DataModel {
	if m != nil {
		return m.DataModel
	}
	return TxReadWriteSet_KV
}

func (m *TxReadWriteSet) GetNsRwset() []*NsReadWriteSet {
	if m != nil {
		return m.NsRwset
	}
	return nil
}

func (m *TxReadWriteSet) GetPrivateReadwritesetHash() []byte {
	if m != nil {
		return m.PrivateReadwritesetHash
	}
	return nil
}

// NsReadWriteSet encapsulates the read-write set for a chaincode
type NsReadWriteSet struct {
	Namespace             string                          `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Rwset                 []byte                          `protobuf:"bytes,2,opt,name=rwset,proto3" json:"rwset,omitempty"`
	CollectionHashedRwset []*CollectionHashedReadWriteSet `protobuf:"bytes,3,rep,name=collection_hashed_rwset,json=collectionHashedRwset" json:"collection_hashed_rwset,omitempty"`
}

func (m *NsReadWriteSet) Reset()                    { *m = NsReadWriteSet{} }
func (m *NsReadWriteSet) String() string            { return proto.CompactTextString(m) }
func (*NsReadWriteSet) ProtoMessage()               {}
func (*NsReadWriteSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NsReadWriteSet) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *NsReadWriteSet) GetRwset() []byte {
	if m != nil {
		return m.Rwset
	}
	return nil
}

func (m *NsReadWriteSet) GetCollectionHashedRwset() []*CollectionHashedReadWriteSet {
	if m != nil {
		return m.CollectionHashedRwset
	}
	return nil
}

// CollectionHashedReadWriteSet encapsulate the hashed representation for the private read-write set for a collection
type CollectionHashedReadWriteSet struct {
	CollectionName string `protobuf:"bytes,1,opt,name=collection_name,json=collectionName" json:"collection_name,omitempty"`
	HashedRwset    []byte `protobuf:"bytes,2,opt,name=hashed_rwset,json=hashedRwset,proto3" json:"hashed_rwset,omitempty"`
}

func (m *CollectionHashedReadWriteSet) Reset()                    { *m = CollectionHashedReadWriteSet{} }
func (m *CollectionHashedReadWriteSet) String() string            { return proto.CompactTextString(m) }
func (*CollectionHashedReadWriteSet) ProtoMessage()               {}
func (*CollectionHashedReadWriteSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CollectionHashedReadWriteSet) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CollectionHashedReadWriteSet) GetHashedRwset() []byte {
	if m != nil {
		return m.HashedRwset
	}
	return nil
}

// TxPvtReadWriteSet encapsulate the private read-write set for a transaction
type TxPvtReadWriteSet struct {
	DataModel  TxReadWriteSet_DataModel `protobuf:"varint,1,opt,name=data_model,json=dataModel,enum=rwset.TxReadWriteSet_DataModel" json:"data_model,omitempty"`
	NsPvtRwset []*NsPvtReadWriteSet     `protobuf:"bytes,2,rep,name=ns_pvt_rwset,json=nsPvtRwset" json:"ns_pvt_rwset,omitempty"`
}

func (m *TxPvtReadWriteSet) Reset()                    { *m = TxPvtReadWriteSet{} }
func (m *TxPvtReadWriteSet) String() string            { return proto.CompactTextString(m) }
func (*TxPvtReadWriteSet) ProtoMessage()               {}
func (*TxPvtReadWriteSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TxPvtReadWriteSet) GetDataModel() TxReadWriteSet_DataModel {
	if m != nil {
		return m.DataModel
	}
	return TxReadWriteSet_KV
}

func (m *TxPvtReadWriteSet) GetNsPvtRwset() []*NsPvtReadWriteSet {
	if m != nil {
		return m.NsPvtRwset
	}
	return nil
}

// NsPvtReadWriteSet encapsulates the private read-write set for a chaincode
type NsPvtReadWriteSet struct {
	Namespace          string                       `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	CollectionPvtRwset []*CollectionPvtReadWriteSet `protobuf:"bytes,2,rep,name=collection_pvt_rwset,json=collectionPvtRwset" json:"collection_pvt_rwset,omitempty"`
}

func (m *NsPvtReadWriteSet) Reset()                    { *m = NsPvtReadWriteSet{} }
func (m *NsPvtReadWriteSet) String() string            { return proto.CompactTextString(m) }
func (*NsPvtReadWriteSet) ProtoMessage()               {}
func (*NsPvtReadWriteSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NsPvtReadWriteSet) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *NsPvtReadWriteSet) GetCollectionPvtRwset() []*CollectionPvtReadWriteSet {
	if m != nil {
		return m.CollectionPvtRwset
	}
	return nil
}

// CollectionPvtReadWriteSet encapsulates the private read-write set for a collection
type CollectionPvtReadWriteSet struct {
	CollectionName string `protobuf:"bytes,1,opt,name=collection_name,json=collectionName" json:"collection_name,omitempty"`
	Rwset          []byte `protobuf:"bytes,2,opt,name=rwset,proto3" json:"rwset,omitempty"`
}

func (m *CollectionPvtReadWriteSet) Reset()                    { *m = CollectionPvtReadWriteSet{} }
func (m *CollectionPvtReadWriteSet) String() string            { return proto.CompactTextString(m) }
func (*CollectionPvtReadWriteSet) ProtoMessage()               {}
func (*CollectionPvtReadWriteSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CollectionPvtReadWriteSet) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CollectionPvtReadWriteSet) GetRwset() []byte {
	if m != nil {
		return m.Rwset
	}
	return nil
}

func init() {
	proto.RegisterType((*TxReadWriteSet)(nil), "rwset.TxReadWriteSet")
	proto.RegisterType((*NsReadWriteSet)(nil), "rwset.NsReadWriteSet")
	proto.RegisterType((*CollectionHashedReadWriteSet)(nil), "rwset.CollectionHashedReadWriteSet")
	proto.RegisterType((*TxPvtReadWriteSet)(nil), "rwset.TxPvtReadWriteSet")
	proto.RegisterType((*NsPvtReadWriteSet)(nil), "rwset.NsPvtReadWriteSet")
	proto.RegisterType((*CollectionPvtReadWriteSet)(nil), "rwset.CollectionPvtReadWriteSet")
	proto.RegisterEnum("rwset.TxReadWriteSet_DataModel", TxReadWriteSet_DataModel_name, TxReadWriteSet_DataModel_value)
}

func init() { proto.RegisterFile("ledger/rwset/rwset.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x53, 0xcd, 0xae, 0xd2, 0x40,
	0x18, 0xb5, 0x97, 0xdc, 0xab, 0xfd, 0x2e, 0xa9, 0xde, 0xf1, 0x12, 0x4a, 0x42, 0x62, 0xc5, 0x85,
	0xc4, 0x45, 0xab, 0xb8, 0x63, 0xe1, 0x42, 0x5d, 0x90, 0x18, 0x89, 0x19, 0x89, 0x26, 0xb8, 0x68,
	0x86, 0xf6, 0x93, 0xd6, 0xf4, 0x2f, 0x33, 0x23, 0xe0, 0x03, 0xb8, 0xf6, 0x19, 0x7c, 0x26, 0x5f,
	0xc8, 0x74, 0xa6, 0x40, 0x5b, 0xfc, 0x5b, 0xb8, 0x21, 0xcc, 0x37, 0xe7, 0xe4, 0x9c, 0x33, 0xa7,
	0x1f, 0xd8, 0x09, 0x86, 0x6b, 0xe4, 0x1e, 0xdf, 0x0a, 0x94, 0xfa, 0xd7, 0x2d, 0x78, 0x2e, 0x73,
	0x72, 0xae, 0x0e, 0xa3, 0x1f, 0x06, 0x58, 0x8b, 0x1d, 0x45, 0x16, 0xbe, 0xe7, 0xb1, 0xc4, 0xb7,
	0x28, 0xc9, 0x33, 0x80, 0x90, 0x49, 0xe6, 0xa7, 0x79, 0x88, 0x89, 0x6d, 0x38, 0xc6, 0xd8, 0x9a,
	0xdc, 0x73, 0x35, 0xb7, 0x09, 0x75, 0x5f, 0x32, 0xc9, 0x5e, 0x97, 0x30, 0x6a, 0x86, 0xfb, 0xbf,
	0xe4, 0x31, 0xdc, 0xca, 0x84, 0xaf, 0xf0, 0xf6, 0x99, 0xd3, 0x19, 0x5f, 0x4e, 0x7a, 0x15, 0x7b,
	0x2e, 0xea, 0x6c, 0x7a, 0x33, 0x13, 0xb4, 0x9c, 0x93, 0x29, 0x0c, 0x0a, 0x1e, 0x6f, 0x98, 0x44,
	0x9f, 0x23, 0x0b, 0xb7, 0x25, 0x40, 0xa0, 0xf4, 0x23, 0x26, 0x22, 0xbb, 0xe3, 0x18, 0xe3, 0x2e,
	0xed, 0x57, 0x00, 0x5a, 0xbb, 0x9f, 0x31, 0x11, 0x8d, 0xee, 0x82, 0x79, 0x70, 0x41, 0x2e, 0xe0,
	0xec, 0xd5, 0xbb, 0x3b, 0x37, 0x46, 0xdf, 0x0d, 0xb0, 0x9a, 0x62, 0x64, 0x08, 0x66, 0xc6, 0x52,
	0x14, 0x05, 0x0b, 0x50, 0x85, 0x32, 0xe9, 0x71, 0x40, 0xae, 0xe1, 0x7c, 0x6f, 0xb8, 0x54, 0xd3,
	0x07, 0xf2, 0x01, 0xfa, 0x41, 0x9e, 0x24, 0x18, 0xc8, 0x38, 0xcf, 0x94, 0x1b, 0x0c, 0xab, 0x60,
	0x1d, 0x15, 0xec, 0x41, 0x15, 0xec, 0xc5, 0x01, 0x35, 0x53, 0xa0, 0x46, 0xcc, 0x5e, 0xd0, 0xbe,
	0x55, 0x2f, 0xff, 0x09, 0x86, 0x7f, 0xa2, 0x91, 0x87, 0x70, 0xbb, 0x26, 0x5e, 0x5a, 0xad, 0x6c,
	0x5b, 0xc7, 0xf1, 0x9c, 0xa5, 0x48, 0xee, 0x43, 0xb7, 0x61, 0x4d, 0x47, 0xb8, 0x8c, 0x6a, 0x5a,
	0xdf, 0x0c, 0xb8, 0x5a, 0xec, 0xde, 0x6c, 0xe4, 0x7f, 0x2d, 0x7a, 0x0a, 0xdd, 0x4c, 0xf8, 0xc5,
	0x46, 0x36, 0xca, 0xb6, 0x0f, 0x65, 0xb7, 0xf4, 0x28, 0x64, 0x6a, 0xa4, 0x1c, 0x7d, 0x35, 0xe0,
	0xea, 0x04, 0xf1, 0x97, 0x92, 0x28, 0x5c, 0xd7, 0x5e, 0xa4, 0xad, 0xeb, 0x9c, 0x74, 0xd1, 0xd6,
	0x27, 0x41, 0xe3, 0x4a, 0xf9, 0x58, 0xc2, 0xe0, 0xb7, 0x84, 0x7f, 0xaf, 0xe0, 0x97, 0x9f, 0xcf,
	0x73, 0x1f, 0x1e, 0xe5, 0x7c, 0xed, 0x46, 0x5f, 0x0a, 0xe4, 0x7a, 0x0f, 0xdd, 0x8f, 0x6c, 0xc5,
	0xe3, 0x40, 0xaf, 0xa0, 0x70, 0xab, 0xa1, 0x42, 0x2f, 0x9f, 0xac, 0x63, 0x19, 0x7d, 0x5e, 0xb9,
	0x41, 0x9e, 0x7a, 0x35, 0x8a, 0xa7, 0x29, 0x9e, 0xa6, 0x78, 0xf5, 0x7d, 0x5e, 0x5d, 0xa8, 0xe1,
	0xd3, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0x0c, 0x1a, 0x30, 0xe6, 0x03, 0x00, 0x00,
}
